# Generated by Django 4.2.3 on 2023-07-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookListDRF', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='BookListDRF_price_01836c_idx',
        ),
    ]
